//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongKham.Models.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyPhongKham.Models.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khám không được phép nhỏ hơn ngày hiện tại!.
        /// </summary>
        public static string Error_AOfDateNotLessNow {
            get {
                return ResourceManager.GetString("Error_AOfDateNotLessNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được phép lớn hơn ngày hiện tại!.
        /// </summary>
        public static string Error_BOfDateNotGreatNow {
            get {
                return ResourceManager.GetString("Error_BOfDateNotGreatNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải chứa ít nhất 1 chữ hoa, 1 chữ thường, 1 số và 1 ký tự đặc biệt.
        /// </summary>
        public static string Error_ChangePassword {
            get {
                return ResourceManager.GetString("Error_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công!.
        /// </summary>
        public static string Error_Create {
            get {
                return ResourceManager.GetString("Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công!.
        /// </summary>
        public static string Error_Delete {
            get {
                return ResourceManager.GetString("Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu không thành công!.
        /// </summary>
        public static string Error_Edit {
            get {
                return ResourceManager.GetString("Error_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không được phép để trống!.
        /// </summary>
        public static string Error_EmailNotEmpty {
            get {
                return ResourceManager.GetString("Error_EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ Group 7 để được trợ giúp!.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ được phép đăng ký 1 ca khám có 3 bệnh nhân, vui lòng chọn giờ khác!.
        /// </summary>
        public static string Error_GioKhamExist {
            get {
                return ResourceManager.GetString("Error_GioKhamExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ khám không được phép để trống!.
        /// </summary>
        public static string Error_GioKhamNotEmpty {
            get {
                return ResourceManager.GetString("Error_GioKhamNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ khám không tồn tại, liên hệ Nhóm 7 để được trợ giúp!.
        /// </summary>
        public static string Error_GioKhamNotExist {
            get {
                return ResourceManager.GetString("Error_GioKhamNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ khám của bác sĩ không tồn tại, vui lòng chọn đúng!.
        /// </summary>
        public static string Error_GioKhamOfBacSiNotExist {
            get {
                return ResourceManager.GetString("Error_GioKhamOfBacSiNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bệnh nhân không được phép để trống!.
        /// </summary>
        public static string Error_HoTenNotEmpty {
            get {
                return ResourceManager.GetString("Error_HoTenNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được phép có số!.
        /// </summary>
        public static string Error_HoTenNotNumber {
            get {
                return ResourceManager.GetString("Error_HoTenNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bác sĩ đã tồn tại!.
        /// </summary>
        public static string Error_MaBacSiDuplicated {
            get {
                return ResourceManager.GetString("Error_MaBacSiDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bác sĩ không được phép để trống!.
        /// </summary>
        public static string Error_MaBacSiNotEmpty {
            get {
                return ResourceManager.GetString("Error_MaBacSiNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bệnh nhân đã tồn tại!.
        /// </summary>
        public static string Error_MaBenhNhanDuplicated {
            get {
                return ResourceManager.GetString("Error_MaBenhNhanDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bệnh nhân không được phép để trống!.
        /// </summary>
        public static string Error_MaBenhNhanNotEmpty {
            get {
                return ResourceManager.GetString("Error_MaBenhNhanNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khám không được phép để trống!.
        /// </summary>
        public static string Error_NgayKhamNotEmpty {
            get {
                return ResourceManager.GetString("Error_NgayKhamNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại!.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được phép có chữ!.
        /// </summary>
        public static string Error_PhoneNumberNotLetter {
            get {
                return ResourceManager.GetString("Error_PhoneNumberNotLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ!.
        /// </summary>
        public static string Error_ValidData {
            get {
                return ResourceManager.GetString("Error_ValidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng, vui lòng nhập lại!.
        /// </summary>
        public static string Error_ValidEmail {
            get {
                return ResourceManager.GetString("Error_ValidEmail", resourceCulture);
            }
        }
    }
}
